! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module callback
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! PUBLIC METHODS AND TYPES

type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
end type

 public :: passthrough
 public :: enquote
 public :: join_transformed

 ! PARAMETERS
 type(C_FUNPTR), protected, public, &
   bind(C, name="swigc_enquote_cb") :: enquote_cb

 ! WRAPPER DECLARATIONS
 interface
function swigc_passthrough(farg1) &
bind(C, name="swigc_passthrough") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: SwigArrayWrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: fresult
end function


subroutine SWIG_free(ptr) &
  bind(C, name="free")
 use, intrinsic :: ISO_C_BINDING
 type(C_PTR), value :: ptr
end subroutine

function swigc_enquote(farg1) &
bind(C, name="swigc_enquote") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: SwigArrayWrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: fresult
end function

function swigc_join_transformed(farg1, farg2) &
bind(C, name="swigc_join_transformed") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: SwigArrayWrapper
type(SwigArrayWrapper) :: farg1
type(C_FUNPTR), value :: farg2
type(SwigArrayWrapper) :: fresult
end function

 end interface


contains
 ! FORTRAN PROXY CODE

subroutine SWIG_string_to_chararray(string, chars, wrap)
  use, intrinsic :: ISO_C_BINDING
  character(kind=C_CHAR, len=*), intent(IN) :: string
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(OUT) :: chars
  type(SwigArrayWrapper), intent(OUT) :: wrap
  integer :: i

  allocate(character(kind=C_CHAR) :: chars(len(string) + 1))
  do i=1,len(string)
    chars(i) = string(i:i)
  end do
  i = len(string) + 1
  chars(i) = C_NULL_CHAR ! C string compatibility
  wrap%data = c_loc(chars)
  wrap%size = len(string)
end subroutine


subroutine SWIG_chararray_to_string(wrap, string)
  use, intrinsic :: ISO_C_BINDING
  type(SwigArrayWrapper), intent(IN) :: wrap
  character(kind=C_CHAR, len=:), allocatable, intent(OUT) :: string
  character(kind=C_CHAR), dimension(:), pointer :: chars
  integer(kind=C_SIZE_T) :: i
  call c_f_pointer(wrap%data, chars, [wrap%size])
  allocate(character(kind=C_CHAR, len=wrap%size) :: string)
  do i=1, wrap%size
    string(i:i) = chars(i)
  enddo
end subroutine

function passthrough(s) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(kind=C_CHAR, len=:), allocatable :: swig_result
character(kind=C_CHAR, len=*), target :: s
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_chars
type(SwigArrayWrapper) :: fresult 
type(SwigArrayWrapper) :: farg1 

call SWIG_string_to_chararray(s, farg1_chars, farg1)
fresult = swigc_passthrough(farg1)
call SWIG_chararray_to_string(fresult, swig_result)
call SWIG_free(fresult%data)
end function

function enquote(s) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(kind=C_CHAR, len=:), allocatable :: swig_result
character(kind=C_CHAR, len=*), target :: s
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_chars
type(SwigArrayWrapper) :: fresult 
type(SwigArrayWrapper) :: farg1 

call SWIG_string_to_chararray(s, farg1_chars, farg1)
fresult = swigc_enquote(farg1)
call SWIG_chararray_to_string(fresult, swig_result)
call SWIG_free(fresult%data)
end function

function join_transformed(joiner, cb) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(kind=C_CHAR, len=:), allocatable :: swig_result
character(kind=C_CHAR, len=*), target :: joiner
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_chars
type(C_FUNPTR), intent(in), value :: cb
type(SwigArrayWrapper) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(C_FUNPTR) :: farg2 

call SWIG_string_to_chararray(joiner, farg1_chars, farg1)
farg2 = cb
fresult = swigc_join_transformed(farg1, farg2)
call SWIG_chararray_to_string(fresult, swig_result)
call SWIG_free(fresult%data)
end function


end module
